joint_limits:
  robot1_joint1:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: true
    max_acceleration: 3.75
  robot1_joint2:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: true
    max_acceleration: 1.875
  robot1_joint3:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: true
    max_acceleration: 2.5
  robot1_joint4:
    has_velocity_limits: true
    max_velocity: 2.175
    has_acceleration_limits: true
    max_acceleration: 3.125
  robot1_joint5:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: true
    max_acceleration: 3.75
  robot1_joint6:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: true
    max_acceleration: 5.0
  robot1_joint7:
    has_velocity_limits: true
    max_velocity: 2.61
    has_acceleration_limits: true
    max_acceleration: 5.0
  robot1_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.0
  robot1_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.0
