controller_names:
- joint_trajectory_controller
- gripper_trajectory_controller
joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
  - robot1_joint1
  - robot1_joint2
  - robot1_joint3
  - robot1_joint4
  - robot1_joint5
  - robot1_joint6
  - robot1_joint7
gripper_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
  - robot1_finger_joint1
  - robot1_finger_joint2
